onlyBuiltDependencies:
  - '@reown/appkit'
  - bufferutil
  - keccak
  - sharp
  - unrs-resolver
  - utf-8-validate

overrides:
  '@welshare/sdk': link:../../../../Library/pnpm/global/5/node_modules/@welshare/sdk
